// <auto-generated />
using LinkFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LinkFit.Migrations
{
    [DbContext(typeof(CoachContext))]
    [Migration("20170919214653_AthleteDateOfBirth")]
    partial class AthleteDateOfBirth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinkFit.Models.Athlete", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<string>("EntrantCategory");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("LinkFit.Models.ProgramEnrollment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AthleteID");

                    b.Property<int>("TrainingProgramID");

                    b.HasKey("ID");

                    b.HasIndex("AthleteID");

                    b.HasIndex("TrainingProgramID");

                    b.ToTable("ProgramEnrollment");
                });

            modelBuilder.Entity("LinkFit.Models.TrainingProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("TrainingProgram");
                });

            modelBuilder.Entity("LinkFit.Models.ProgramEnrollment", b =>
                {
                    b.HasOne("LinkFit.Models.Athlete", "Athlete")
                        .WithMany("ProgramEnrollments")
                        .HasForeignKey("AthleteID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinkFit.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("ProgramEnrollments")
                        .HasForeignKey("TrainingProgramID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
